openapi: 3.0.1
info:
  title: WebApplication1
  version: '1.0'
paths:
  /api/Order:
    get:
      tags:
        - Order
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderModel'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderModel'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderModel'
    post:
      tags:
        - Order
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderModel'
          text/json:
            schema:
              $ref: '#/components/schemas/OrderModel'
          application/*+json:
            schema:
              $ref: '#/components/schemas/OrderModel'
      responses:
        '200':
          description: Success
  /api/Order/{id}:
    get:
      tags:
        - Order
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/OrderModel'
            application/json:
              schema:
                $ref: '#/components/schemas/OrderModel'
            text/json:
              schema:
                $ref: '#/components/schemas/OrderModel'
    delete:
      tags:
        - Order
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
components:
  schemas:
    OrderModel:
      type: object
      properties:
        id:
          type: integer
          format: int32
        companyId:
          type: string
          nullable: true
        orderNumber:
          type: string
          nullable: true
        orderDate:
          type: string
          format: date-time
          nullable: true
        warehouse:
          type: string
          nullable: true
        customerName:
          type: string
          nullable: true
      additionalProperties: false
